[program:afisha-video-proxy]
directory=/root/afisha-bot
command=/root/afisha-bot/venv/bin/python -m bot.proxy.server
autostart=true
autorestart=true
user=root
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/var/log/afisha-video-proxy.out.log
stderr_logfile=/var/log/afisha-video-proxy.err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
